//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskTracker_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class checklist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public checklist()
        {
            this.isQuestionOfs = new HashSet<isQuestionOf>();
        }
    
        public int checklistID { get; set; }
        public string name { get; set; }
        public int managerID { get; set; }
        public System.DateTime createdAt { get; set; }
        public Nullable<System.DateTime> modifiedAt { get; set; }
        public Nullable<bool> deleted { get; set; }
    
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<isQuestionOf> isQuestionOfs { get; set; }
        public virtual submission submission { get; set; }
    }
}
