//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskTracker_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class submission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public submission()
        {
            this.answers = new HashSet<answer>();
        }
    
        public int submissionID { get; set; }
        public int checklistID { get; set; }
        public int userID { get; set; }
        public System.DateTime submissionDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<answer> answers { get; set; }
        public virtual checklist checklist { get; set; }
        public virtual user user { get; set; }
    }
}
